### ISSUE TITLE
Add a location to scan or enter barcode values

### ISSUE THREAD

**Issue by davidlougheed** [ColauttiLab/PyTrackDat#6]
For the reverse of generating barcodes, it should be easy to scan and search for their corresponding items using a search box on the dashboard.

**Comment by ColauttiLab** [comment]
A simple text search should work in most cases, since the scanner usually just outputs text as a basic input device. One potential complication is that sometimes the scanner will append additional characters like \t or \n or \r\n or , to facilitate data entry into spreadsheet or text documents.

**Comment by davidlougheed** [comment]
Added in 38d61a3be0aca25a9bd4e82400b3774aab1b8714
